### ISSUE TITLE
tests do not run correctly on solidus_gateway master -- Factory already registered: skrill_quick_checkout

### ISSUE THREAD

**Issue by jasonfb** [solidusio/solidus_gateway#9]
```
jason@Jasons-MB-Air-2:solidus_gateway (master)$ be rspec spec/*
Coverage report generated for RSpec to /Users/jason/Projects/Mack-Weldon/solidus_gateway/coverage. 332 / 828 LOC (40.1%) covered.
/Users/jason/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.5.0/lib/factory_girl/decorator.rb:10:in `method_missing': Factory already registered: skrill_quick_checkout (FactoryGirl::DuplicateDefinitionError)
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.5.0/lib/factory_girl/decorator/disallows_duplicates_registry.rb:6:in `register'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.5.0/lib/factory_girl.rb:70:in `block in register_factory'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.5.0/lib/factory_girl.rb:69:in `each'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.5.0/lib/factory_girl.rb:69:in `register_factory'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:20:in `factory'
	from /Users/jason/Projects/Mack-Weldon/solidus_gateway/spec/factories/skrill_factory.rb:2:in `block in <top (required)>'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:49:in `run'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:7:in `define'
	from /Users/jason/Projects/Mack-Weldon/solidus_gateway/spec/factories/skrill_factory.rb:1:in `<top (required)>'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:20:in `block (2 levels) in find_definitions'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:19:in `each'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:19:in `block in find_definitions'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:15:in `each'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:15:in `find_definitions'
	from /Users/jason/Projects/Mack-Weldon/solidus_gateway/spec/spec_helper.rb:49:in `block in <top (required)>'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.4.1/lib/rspec/core.rb:97:in `configure'
	from /Users/jason/Projects/Mack-Weldon/solidus_gateway/spec/spec_helper.rb:22:in `<top (required)>'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `each'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:102:in `setup'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in `run'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
	from /Users/jason/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.4.1/exe/rspec:4:in `<top (required)>'
	from /Users/jason/.rvm/gems/ruby-2.1.5/bin/rspec:23:in `load'
	from /Users/jason/.rvm/gems/ruby-2.1.5/bin/rspec:23:in `<main>'
	from /Users/jason/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jason/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jasonfb** [comment]
I see it registered inside of solidus_gateway/spec/factories/skrill_factory.rb but I can't seem to find where FG is loading it first-- I suspect one of the dependent gems

**Comment by jasonfb** [comment]
this is reproducible on master: 1. clone the repo, 2. run ```rake test_app```, 3. run ```rake spec/*```

**Comment by jhawthorn** [comment]
Running `rspec spec/*` (I assume `rake` was a typo) will not work, since that will load the spec_helper twice (causing your `skrill_quick_checkout` issue). Just run `rspec` or `rspec spec`.

**Comment by jasonfb** [comment]
confirmed ```rake spec/*``` was a typo, what I meant was ```bundle exec rspec spec/*```

you are indeed correct, ```bundle exec rspec spec``` works as expected, my mistake. 

Thanks for the feedback!
